### ISSUE TITLE
create db to save records

### ISSUE THREAD

**Issue by chzlithoo** [allmeat/connect6#35]
domain options:
* GCP
* AWS
* google drive

db options:
* RDB
* no-sql
* plain text

**Comment by hyoungseok** [comment]
1. Create account at AWS
2.  Amazon RDS
3. Create DB
   1. standard
   2. MariaDB
   3. free tier
   4. password
   5. not using auto-scaling
   6. new VPC
   7. allow public access
   8. new VPC group
   9. initial DB name
   10. not using auto-backuo
   11. not using minor version auto-update
4. allow VPC inbound setting
5. connect DB
